services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=as-docker-cluster
      - discovery.type=single-node # Essential for a single-node setup
      - xpack.security.enabled=false # Disable security for simpler local development (adjust for production)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Allocate memory for Elasticsearch
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data # Persist data
    ports:
      - 9200:9200 # Expose HTTP API
    #      - 9300:9300 # Expose Transport Layer (for inter-node communication)
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0 # Replace with your desired Kibana version
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200 # Assumes Elasticsearch service named 'elasticsearch'
    depends_on:
      - elasticsearch
    networks:
      - elastic

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: h2-file
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

volumes:
  elasticsearch-data:
    driver: local
  keycloak-data:
    driver: local

networks:
  elastic:
    driver: bridge