services:
  backend:
    build: .
    image: my-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/restaurant-review
    depends_on:
      - elasticsearch
      - keycloak
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=as-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
    networks:
      - elastic

volumes:
  elasticsearch-data:
    driver: local
  keycloak-data:
    driver: local

networks:
  elastic:
    driver: bridge